# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rrGAJ5rodBdHK5P25Gc6DubbT0_GboA
"""

#Takes two numbers as input from the user.
a=input("Enter First Number")
b=input("Enter Second Number")

# Performs the basic mathematical operations on these two numbers:
#o	Addition
#o	Subtraction
#o	Multiplication
#o	Division
a = int(input("Enter First Number: "))
b = int(input("Enter Second Number: "))

c = a + b
d = a - b
e = a * b
f = a / b
# Display Result of Each Operations
print("Addition:", c)
print("Subtraction:", d)
print("Multiplication:", e)
print("Division:", f)

# 1. Take first name and last name as input
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

# 2. Concatenate to get full name
full_name = first_name + " " + last_name

# 3. Print personalized greeting
print("Hello, " + full_name + "! Welcome! to the python program")